export const EXCLUDE_STYLE_SUGGESTIONS = [
  // vocal processing / vocal delivery
  'autotune',
  'heavy autotune',
  'robotic vocals',
  'vocoder',
  'talkbox',
  'chipmunk vocals',
  'formant shift',
  'pitch correction artifacts',
  'aggressive vocals',
  'screamed vocals',
  'growls',
  'vocal fry',
  'whispered',
  'spoken',
  'spoken word',
  'rap',
  'fast rap',
  'mumble rap',
  'ad-libs',
  'excessive ad-libs',
  'callouts',
  'crowd chants',

  // drums / rhythm
  'trap hats',
  'rapid hi-hats',
  'drill',
  'jersey club',
  'breakcore',
  'dnb',
  'drum and bass',
  'dubstep',
  'hardstyle',
  'gabber',
  'double kick',
  'blast beats',
  'overly busy drums',
  'fast tempo',
  'very fast tempo',
  'half-time drop',

  // genre / aesthetic exclusions
  'hyperpop',
  'screamo',
  'metal',
  'death metal',
  'black metal',
  'nu metal',
  'industrial metal',
  'punk',
  'hardcore',
  'emo',
  'phonk',
  'brostep',
  'glitch',
  'experimental noise',
  'lofi',
  'lo-fi aesthetic',

  // guitars / sound design
  'heavy distortion',
  'overdriven guitars',
  'shredding guitar solo',
  'squealing feedback',
  'harsh synths',
  'piercing leads',
  'overly bright mix',

  // mix / production
  'overly reverb',
  'washed-out reverb',
  'muddy mix',
  'overcompressed',
  'brickwall limiting',
  'clipping',
  'excessive bass',
  'boomy low end',
  'overly wide stereo',
  'phasey stereo',
  'no dynamics',

  // arrangement / structure
  'long intro',
  'long outro',
  'no intro hook',
  'no chorus',
  'chorus repetition',
  'repetitive chorus',
  'too repetitive',
  'overly long build up',
  'fake drop',
  'multiple drops',
  'extended instrumental',

  // lyrical / content
  'explicit lyrics',
  'violent lyrics',
] as const;
