export const STYLE_SUGGESTIONS = [
  // genres
  'pop',
  'indie pop',
  'alt pop',
  'hyperpop',
  'electropop',
  'dance pop',
  'pop rock',
  'rock',
  'swedish rock',
  'alternative',
  'indie',
  'indie rock',
  'garage rock',
  'post-punk',
  'punk',
  'hard rock',
  'metal',
  'shoegaze',
  'grunge',
  'electro',
  'electronica',
  'synthpop',
  'synthwave',
  'retrowave',
  'darkwave',
  'new wave',
  'chillwave',
  'wave',
  'trap',
  'hip hop',
  'boom bap',
  'drill',
  'phonk',
  'lofi',
  'lofi hip hop',
  'ambient',
  'dark ambient',
  'cinematic',
  'orchestral',
  'neo-classical',
  'acoustic',
  'folk',
  'indie folk',
  'country',
  'bluegrass',
  'r&b',
  'alt r&b',
  'neo soul',
  'soul',
  'funk',
  'jazz',
  'jazz fusion',
  'bossa nova',
  'latin',
  'reggaeton',
  'afrobeats',
  'dancehall',
  'house',
  'deep house',
  'progressive house',
  'tech house',
  'techno',
  'melodic techno',
  'industrial techno',
  'trance',
  'progressive trance',
  'dnb',
  'drum and bass',
  'breakbeat',
  'uk garage',
  'future garage',
  'dubstep',
  'future bass',
  'downtempo',
  'trip hop',
  'experimental',
  'idm',

  // moods / vibes
  'captivating',
  'dark',
  'uplifting',
  'melancholic',
  'romantic',
  'aggressive',
  'chill',
  'energetic',
  'dreamy',
  'nostalgic',
  'intimate',
  'epic',
  'mysterious',
  'playful',
  'sad',
  'happy',
  'angry',
  'hopeful',
  'bittersweet',
  'euphoric',
  'tense',
  'hypnotic',
  'sensual',
  'brooding',
  'moody',
  'warm',
  'cold',
  'raw',
  'glossy',
  'anthemic',
  'laid-back',
  'uplifting chorus',
  'club vibe',
  'late night',
  'summer vibe',
  'winter vibe',

  // era / aesthetic
  '80s',
  '90s',
  '2000s',
  'retro',
  'vintage',
  'modern',
  'futuristic',
  'analog',
  'lo-fi aesthetic',

  // structure / songwriting
  'catchy hook',
  'big chorus',
  'anthem chorus',
  'verse-pre-chorus-chorus',
  'bridge section',
  'drop',
  'build up',
  'breakdown',
  'instrumental break',

  // tempo / groove
  'slow tempo',
  'mid tempo',
  'uptempo',
  'half-time',
  'four-on-the-floor',
  'shuffle groove',
  'swing',
  'syncopated',
  'driving rhythm',

  // instruments / texture
  'bass guitars',
  'bassline',
  'sub bass',
  'violin',
  'piano',
  'electric piano',
  'strings',
  'orchestral strings',
  'distorted guitars',
  'clean guitars',
  'acoustic guitars',
  'guitar riffs',
  'guitar solo',
  '808',
  'tight drums',
  'minimal drums',
  'no drums',
  'lush pads',
  'arpeggios',
  'synth leads',
  'analog synths',
  'fm synths',
  'warm pads',
  'pluck synths',
  'brass',
  'horn section',
  'flute',
  'saxophone',
  'harp',
  'choir',
  'hand claps',
  'snap',
  'percussion',
  'shakers',
  'congas',
  'tabla',

  // production / mix cues
  'reverb heavy',
  'dry mix',
  'wide stereo',
  'mono verse',
  'punchy mix',
  'clean mix',
  'dirty mix',
  'distorted mix',
  'tape saturation',
  'vinyl crackle',
  'sidechain',
  'gated reverb',
  'big drums',
  'tight mix',
  'minimal mix',
] as const;
