export const VOICE_SUGGESTIONS = [
  // texture / timbre
  'warm',
  'bright',
  'dark',
  'airy',
  'breathy',
  'raspy',
  'gritty',
  'clean',
  'smooth',
  'nasal',
  'deep',
  'soft',
  'husky',
  'smoky',
  'silky',
  'velvety',
  'rich',
  'thin',
  'crisp',
  'round',
  'chesty',
  'breathy head voice',
  'open throat',
  'tight tone',
  'metallic edge',
  'raw',
  'polished',
  'intimate close-mic',

  // range / voice type
  'baritone',
  'tenor',
  'alto',
  'soprano',
  'low register',
  'high register',

  // delivery / attitude
  'intimate',
  'powerful',
  'gentle',
  'aggressive',
  'emotional',
  'melancholic',
  'playful',
  'dramatic',
  'confident',
  'laid-back',
  'urgent',
  'tender',
  'vulnerable',
  'seductive',
  'anthemic',
  'uplifting',
  'stoic',
  'sarcastic',
  'sassy',
  'dreamy',
  'energetic',

  // vocal styles / techniques
  'spoken',
  'melodic',
  'chant',
  'whispered',
  'falsetto',
  'harmonies',
  'double-tracked',
  'ad-libs',
  'belting',
  'vibrato',
  'straight tone',
  'runs',
  'riffing',
  'crooned',
  'shouted',
  'scream',
  'growl',
  'vocal fry',
  'rap vocals',
  'sing-rap',
  'spoken-word',
  'call and response',
  'gang vocals',
  'choir',
  'a cappella',
  'layered vocals',
  'octave doubles',

  // character / casting-ish
  'male vocals',
  'female vocals',
  'duet',
  'androgynous vocals',
  'youthful voice',
  'mature voice',
  'storyteller',

  // production-ish (voice processing / placement)
  'dry vocals',
  'light reverb',
  'big reverb',
  'roomy vocals',
  'vintage tone',
  'modern pop tone',
  'compressed vocals',
  'saturated vocals',
  'tape saturation',
  'slapback delay',
  'delay throws',
  'telephone filter',
  'lo-fi vocal',
  'radio voice',
  'stereo widen',
  'tight tuning',
  'natural tuning',
  'autotune',
  'vocoder',
  'chorus effect',
  'de-essed',
] as const;
